# Generated by Django 2.1 on 2018-08-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_cancel_list',
            fields=[
                ('start', models.CharField(blank=True, max_length=20, null=True)),
                ('terminate', models.CharField(blank=True, max_length=20, null=True)),
                ('bus_num', models.IntegerField()),
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_infomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=20, null=True)),
                ('terminate', models.CharField(blank=True, max_length=20, null=True)),
                ('bus_num', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
