# Generated by Django 2.1 on 2018-08-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_cancel_list',
            name='bus_num',
            field=models.IntegerField(blank=True),
        ),
    ]
