# Generated by Django 2.1 on 2018-08-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0002_auto_20180829_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_cancel_list',
            name='runningstatus',
            field=models.BooleanField(default=False),
        ),
    ]
