# Generated by Django 2.1 on 2018-09-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogflow', '0004_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='card_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
